final: go_fish.o player.o deck.o card.o
	g++ -std=c++11 -otest go_fish.o player.o deck.o card.o
driver: card_demo.cpp player.h deck.h card.h
	g++ -std=c++11 -c go_fish.cpp
player.o: player.cpp player.h deck.h card.h
    g++ -std=c++11 -c deck.cpp
deck.o: deck.cpp deck.h card.h
	g++ -std=c++11 -c deck.cpp
card.o: card.cpp card.h
	g++ -std=c++11 -c card.cpp
